### PR TITLE
release prep

### PR DESCRIPTION
**Pull request by FredericBlum**
@LinguList As requested the release PR. Adapted the following changes:

- cleaned up raw/ and out everything into an raw/archive/ folder
- Added @PromiseDodzi and IndianaTones as Editors (more suitable than Other I think, right?)

### CODE REVIEW

**Comment by FredericBlum** [comment]
Ah, and I was confused about the author list: In the original publication, RObert Forkel is mentioned. And in the ContributorsTable the following:

Laura McPherson 		data collector 	Author
Kirill Prokhorov 		data collector 	Author

Can you give me some insights into the who-is-who for this dataset?

We also need to add this concept list to Concepticon, possibly before adding this to LB2.0

**Review by LinguList — APPROVED** [review]

**Comment by FredericBlum** [comment]
@LinguList Could you briefly comment on the Contributors, as specified above?

**Comment by LinguList** [comment]
I just saw that dogonlanguages.org is down. So I cannot check the authors. It should follow from their website, I think.

**Comment by FredericBlum** [comment]
Thanks to @xrotwang, we have the new homepage: https://dogonlanguages.info/

He does not want to be an editor of the cited dataset. So probably the current ContributorsTable can stay as it is?

**Comment by LinguList** [comment]
Yes, sounds reasonable!

**Review by chrzyki — APPROVED** [review]
Thanks for the cleanup. :)

**Pull request merged**
